services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    volumes:
      - ./db.sqlite3:/code/db/

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mac/:/code
    ports:
      - "8000:8000"